name = "cloudflare-neon-email"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
FORWARD_EMAIL = "allisteraall@gmail.com"

# Add your Neon database connection string as a secret:
# wrangler secret put DATABASE_URL

# Add your Anthropic API key as a secret:
# wrangler secret put ANTHROPIC_API_KEY
